add_newline = false

[line_break]
disabled = true


[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = true
show_always = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"

[sudo]
format = '[as $symbol]($style)'
symbol = 'sudo '
style = 'bold blue'
disabled = false

[cmd_duration]
disabled = true

[golang]
symbol = " "

[rust]
symbol = "󱘗 "

[python]
symbol = " "

[nodejs]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '
